---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: infra-support-info-storage
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
